### ISSUE TITLE
Different behaviour in command palette and menu

### ISSUE THREAD

**Issue by Fank** [atom/package-generator#22]
I created a package called `default-language2`, I saw this the new created package contains a view so i wanted to toggle it, first i used the menu entry `Packages` -> `default-language2` -> `Toggle` which works as expected:
![fine](https://cloud.githubusercontent.com/assets/1900106/6980699/52a87fc4-d9f6-11e4-9252-3fab05a6dee4.gif)

But if i use the command palette it will only open the view because `@modalPanel.isVisible()` is always `false`:
![bugged](https://cloud.githubusercontent.com/assets/1900106/6980714/8d75eca4-d9f6-11e4-8fea-c9201d743c27.gif)

Here is the toggle function (i added `@modalPanel.isVisible()` to the console log):
```coffeescript
  toggle: ->
    console.log 'DefaultLanguage2 was toggled!', @modalPanel.isVisible()

    if @modalPanel.isVisible()
      @modalPanel.hide()
    else
      @modalPanel.show()
```

I don't know if this is placed in the wrong repo but i used the `package-generator` to create this package and maybe it is related to this.

**Comment by lee-dohm** [comment]
If you show the Command Palette and then just press <kbd>ESC</kbd>, is the `DefaultLanguage2` panel still visible? It could be that opening the Command Palette dismisses the modal panel ... therefore, it is behaving correctly according to the logic you posted.

**Comment by Fank** [comment]
Pressing ESC -> no effect, panel is still there

**Comment by izuzak** [comment]
> > If you show the Command Palette and then just press ESC, is the DefaultLanguage2 panel still visible?

> Pressing ESC -> no effect, panel is still there

@Fank Hmmm, I'm not sure but I think you misunderstood @lee-dohm's question. Just pressing `esc` won't do anything. However, opening the Command Palette and then dismissing it with `esc` should. Here's a GIF of me doing that:

![pack](https://cloud.githubusercontent.com/assets/38924/8501836/b1eca99c-21a9-11e5-9d03-59839812f7f4.gif)

Also, if you open the devtools, then toggle the panel for your generated package, then use the devtools selection tool to focus on the panel element in the Elements view, and finally trigger the command palette -- you should notice that the `<atom-panel>` element gets a `style="display: none;"` attribute as soon as the command palette is shown.

Are you seeing the same behavior? If you are, then I think we can close this issue.

**Comment by Fank** [comment]
@izuzak yea can be closed. I didn't noticed that the "panel" will be hidden if the command palette will be shown.
