### ISSUE TITLE
Wrong default path for 'Generate Syntax Theme'

### ISSUE THREAD

**Issue by danielbayley** [atom/package-generator#29]
Similar to #27, although I don't think identical.

Following [the tutorial](https://atom.io/docs/v0.61.0/creating-a-theme) to create a syntax theme, when doing 'Generate Syntax Theme' from the command palette, I get `~/Library/Application Support/Atom/․atom/packages/my-theme-syntax` as the default path (since my `ATOM_HOME` is set to `~/Library/Application Support/Atom`). However the `.atom/packages` suffix shouldn't be there.

OS X Yosemite 10.10.4
Atom 1.0.2

**Comment by thomasjo** [comment]
First of all the tutorial you're referencing is wildly outdated, and secondly no longer supported. The last valid version of Atom where it was supported was v0.186.0. You should follow the corresponding tutorial in the Atom Flight Manual instead, i.e. [*Package: Word Count*](https://atom.io/docs/latest/hacking-atom-package-word-count).

The package generation is (to my knowledge) not affected by `ATOM_HOME` which can readily be verified by looking at the [relevant code](https://github.com/atom/package-generator/blob/v0.40.0/lib/package-generator-view.coffee#L69-L72). It is however affected by the configuration variable `core.projectHome` as well as the `apm` specific environment variable `ATOM_REPOS_HOME`. Check what those two are set to.

I'm unable to reproduce.

**Comment by danielbayley** [comment]
> The last valid version of Atom where it was supported was v0.186.0.

Ah, that explains why `You might want the latest version of this page` goes to that version.

My `ATOM_REPOS_HOME` is set to `ATOM_HOME/dev/packages`.

I'll check out the new flight manual, thanks.
